### ISSUE TITLE
gestion de proyectos infografia

### ISSUE THREAD

**Issue by ang3-l32** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-ang3-l32#2]
[GP_AngelesGonzalezMartinez _infografia 1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-ang3-l32/files/12479639/GP_AngelesGonzalezMartinez._infografia.1.pdf)

**Comment by ElisabetRD** [comment]
18% falta bibliografia

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
